markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: 郑万耕                                                # 博客名称
    description: 没有一颗心会因为追求梦想而受伤。                                         # 博客描述
    title: IT民工                                              # 网页标题
    url:                                                 # 博客地址
    duoshuo: 10160302                                            # 多说ID
    tongji: 252c4b9a403bd4a38d64cfcaea7dc382                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: 郑万耕                                                # 作者名称
    email: zwg4219@163.com                                               # 邮箱地址
    weibo: https://github.com/zhengwangeng                                              # 微博地址
    github: https://github.com/zhengwangeng                                              # GitHub地址
    logo: /res/img/logo.jpeg                                                # logo地址
    douban:
        name: 感悟爱与辛福                                            # 豆瓣地址名称
        key: 096c220102f6b52f1c44660308e41f8d                                             # 豆瓣API Key
