# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhengwangeng.github.io
date_format: "ordinal"
title: 感悟爱与幸福
subtitle: "没有一颗心会因为追求梦想而受伤"
description: "郑万耕的个人博客"
keywords: 爱, 幸福, 感悟爱与幸福
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zhengwangeng
organization: Mecare, Inc.
organization_url: http://www.mecare.me
github_username: zhengwangeng
location: Shanghai, China
email: zwg4219@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhengwangeng/zhengwangeng.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhengwangeng
    repo: blog-comments
    oauth:
        client_id: 85e32aed77fba606d011
        client_secret: c293453cbd489f802e280c97a1ba257f0549e373
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhengwangeng
    repo: blog-comments
    clientID: 85e32aed77fba606d011
    clientSecret: c293453cbd489f802e280c97a1ba257f0549e373
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-33793299-1
