# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://zhengwangeng.github.io
date_format: "ordinal"
title: 感悟爱与幸福
subtitle: "没有一颗心会因为追求梦想而受伤"
description: "郑万耕的个人博客"
keywords: 爱, 幸福, 感悟爱与幸福
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zhengwangeng
organization: Mecare, Inc.
organization_url: http://www.mecare.me
location: Shanghai, China
email: zwg4219@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhengwangeng/zhengwangeng.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: zhengwangeng
#douban_username: zhengwangeng
#facebook_username: zhengwangeng
#weibo_username: zhengwangeng
#zhihu_username: zhengwangeng
#twitter_username: zhengwangeng

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: mazhuang
disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, DB, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
